### ISSUE TITLE
Create Author group

### ISSUE THREAD

**Issue by chalothon** [JoeyChiou/ELOEditor#10]
I can create a group but the system don’t show any information after I created a group and number of groups created = 0 
![image](https://cloud.githubusercontent.com/assets/17741066/13631962/4bb6c9b2-e622-11e5-84d1-6e796674b1f9.png)
![image](https://cloud.githubusercontent.com/assets/17741066/13631965/4f0c050a-e622-11e5-9fcb-6908b890ce27.png)

**Comment by yrchen** [comment]
Confirm. :+1:

**Comment by yrchen** [comment]
@JoeyChiou 我確認過這個 bug, 伺服器端會回應 500, 但是我自己測試這個 API 是正常的，我想又是送出格式錯誤的老問題

**Comment by yrchen** [comment]
@JoeyChiou 更新，我測試過 Groups 這個 API, 用 JSON 送 request 沒事，用 Form 送會爛。同樣的 ELOs 的 API 就沒事，不管用 JSON 或是 Form 都正常沒問題

**Comment by yrchen** [comment]
https://github.com/yrchen/CommonRepo/issues/3

**Comment by yrchen** [comment]
@JoeyChiou 在 CommonRepo 上的設定是**只用** JSON parser 處理所有的 requests, 所以大原則應該是把所有的 requests 都轉用 JSON 送，你可能得考慮把這邊一次處理掉比較好

**Comment by yrchen** [comment]
@chalothon Bug fixed. Thanks. :+1: 

https://github.com/yrchen/CommonRepo/commit/72920434955e97e01a0763e849a043e4bbe6f2a8
