### ISSUE TITLE
Search ELO

### ISSUE THREAD

**Issue by chalothon** [JoeyChiou/ELOEditor#11]
- I can search by keyword in local but ELO Preview doesn’t show any information
  ![image](https://cloud.githubusercontent.com/assets/17741066/13631986/6981a23c-e622-11e5-866c-5a170d027b4b.png)
- I cannot search by keyword remote search

**Comment by JoeyChiou** [comment]
@chalothon Because this is a wrong ELO object. You can see there has no structure at the left side, so that the ELO Preview doesn't show any information.

**Comment by JoeyChiou** [comment]
@chalothon v1.1.1 release, resolved this issue.
