### ISSUE TITLE
the number of "GROUPS  CREATED" does not increase after create a new group

### ISSUE THREAD

**Issue by worapots** [JoeyChiou/ELOEditor#13]
### Expected behavior

The number of created groups that user created should show in the dashboard.
### Actual behavior

the number of "GROUPS 
CREATED" does not show/ increase after I created a new group.
![numberofcreatedgroup](https://cloud.githubusercontent.com/assets/380330/13632324/105083fc-e624-11e5-87ea-31857bae2d10.png)
### Steps to reproduce the behavior
1. Goto Social group > Create Author Group
2. filling information and click "create"
3. see a number of "GROUPS  CREATED" in Dashboard.

**Comment by yrchen** [comment]
@TitleUpz The main reason of this issues is the group didn't been created correctly and been reported in #10 .

#10 already been fixed. So this issues should been fixed too. Can you try again? If it works now, please come back here to close this issue.

**Comment by JoeyChiou** [comment]
Release v1.1.2 to resolve this issue.
